apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: wttr-selective-allow
spec:
  selector: allow == "wttr-in"
  types:
  - Egress
  egress:
  - action: Allow
    destination:
      selector: role == 'wttr-in'
